@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueRecordList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueRecordList
UniqueTagList -[hidden]down- UniqueRecordList

UniqueTagList *-right-> "*" Tag
UniqueRecordList -right-> Record

Record -up-> "*" Tag

Record *--> Name
Record *--> Phone
Record *--> Email
Record *--> Address
@enduml
